name: Run pytest

on: [push, pull_request]  # Define when the workflow runs

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Ensure code is available

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pytest requests  # Adjust based on your dependencies

      - name: Run pytest
        uses: pavelzw/pytest-action@v2.2.0
